### ISSUE TITLE
Compilation error: Love::Type mismatch, NotAKindOfDrudgery

### ISSUE THREAD

**Issue by tomharrisonjr** [ruby-no-kai/ruby25#21]
Can you help me resolve the above error?

I assume something is missing in my `CLASSPATH`.  Should I contact Oracle?  Gosh, I hope not...

**Comment by igaiga** [comment]
@tomharrisonjr I think you've mistook repository. This repository is for the Ruby 25th event.

**Comment by tomharrisonjr** [comment]
Sorry, my attempted joke failed.
